AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: ''

Globals:
  Function:
    Runtime: python3.9

Parameters:
  AcmCertificateArn:
    Type: String

  Domain:
    Type: String

Resources:

  BucketWeb:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

  BucketWebPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref BucketWeb
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Resource: !Sub 'arn:aws:s3:::${BucketWeb}/*'
            Principal:
              CanonicalUser: !GetAtt BucketWebOAI.S3CanonicalUserId

  CDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref Domain
        Comment: Web site
        DefaultCacheBehavior:
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          Compress: true
          # DefaultTTL: Double
          # FieldLevelEncryptionId: String
          ForwardedValues:
            # Cookies:
            # Headers:
            QueryString: false
            # QueryStringCacheKeys:
          # LambdaFunctionAssociations:
          # MaxTTL: Double
          # MinTTL: Double
          # SmoothStreaming: Boolean
          TargetOriginId: web
          # TrustedSigners:
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        # IPV6Enabled: boolean-value
        Origins:
          - Id: web
            # ConnectionTimeout: Integer
            # ConnectionAttempts: Integer
            # CustomOriginConfig:
            DomainName: !Sub '${BucketWeb}.s3.amazonaws.com'
            # OriginPath:
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${BucketWebOAI}'
        PriceClass: PriceClass_200
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          # CloudFrontDefaultCertificate: Boolean
          # IamCertificateId: String
          # MinimumProtocolVersion: String
          SslSupportMethod: sni-only
      # Tags:

  BucketWebOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref Domain

  UploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: upload.lambda_handler
      Runtime: python3.9
      CodeUri: src
      Environment:
        Variables:
          BucketWeb: !Ref BucketWeb
      Role: !GetAtt UploadFunctionRole.Arn
      Timeout: 5

  UploadFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunctionUrl'
      FunctionName: !GetAtt UploadFunction.Arn
      Principal: '*'
      FunctionUrlAuthType: NONE

  UploadFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: UploadFunctionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: VisualEditor0
                Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:aws:s3:::${BucketWeb}/u/*'
                  - !Sub 'arn:aws:s3:::gyazo.snca.net/rpp/*'

  UploadFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt UploadFunction.Arn

Outputs:
  Bucket:
    Value: !Ref BucketWeb
  UploadFunctionUrl:
    Value: !GetAtt UploadFunctionUrl.FunctionUrl
